# Generated by Django 4.1 on 2022-08-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(default=3)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workouts_web.trainer')),
                ('type_type_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='workouts_web.workouttype')),
                ('workout_place_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workouts_web.workoutplaces')),
            ],
        ),
        migrations.CreateModel(
            name='AthletesOnTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workouts_web.athlete')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_web.workouts')),
            ],
        ),
    ]
